---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: big-data-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: asia-northeast1-docker.pkg.dev/robust-magpie-479807-f1/my-repo/kafka-producer:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: KAFKA_TOPIC
              value: "football-stream"
            - name: BATCH_SIZE
              value: "500"
            - name: SLEEP_TIME
              value: "0.3"
            - name: CSV_FILE_PATH
              value: "/app/data/full_dataset.csv"
            - name: PRODUCER_LOOP
              value: "false"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---

